target 'iosFood2Fork' do
  use_frameworks!
  platform :ios, '16.0'
  pod 'common', :path => '../common'
  pod 'mokoMvvmFlowSwiftUI', :podspec => 'https://raw.githubusercontent.com/icerockdev/moko-mvvm/release/0.13.0/mokoMvvmFlowSwiftUI.podspec'
end
